### ISSUE TITLE
using Promise breaks breaks with older versions of node

### ISSUE THREAD

**Issue by acolby** [matthew-andrews/shellpromise#4]
I've tried using this project with older versions of node and get the error "Promise is not defined"

this is because older versions don't have Promise... how do you feel about either 1) using a library like Q or Bluebird? or 2.) Shimming Promise... if possible?

Let me know... I can implement it.

**Comment by matthew-andrews** [comment]
I think I just need a notice on the readme like I have for [denodeify](http://GitHub.com/Matthew-Andrews/denodeify) and [isomorphic-fetch](http://GitHub.com/Matthew-Andrews/isomorphic-fetch) saying "bring your own promise library".

I'd happily accept a pull request that update the docs to that effect.

Not so keen on bundling this with a promise library especially as you say it's not needed with newer versions.

**Comment by acolby** [comment]
I suppose this is fair, as shimming the global Promise inside the library would not be cool.  BYOP... i like it.
